kind: pipeline

steps:
- name: test
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  environment: 
    repo_username:
      from_secret: repo_username
    repo_password:
      from_secret: repo_password
  commands:
  - dotnet test --logger "console;verbosity=detailed" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - curl -v -u $repo_username:$repo_password --upload-file src/SimpleWorkflow.Test/coverage.opencover.xml https://repository.decryptology.net/repository/artifacts/SimpleWorkflow.Test/coverage.opencover.xml
- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  environment:
    nuget_api_key:
      from_secret: nuget_api_key
  commands:
  - dotnet pack
  - dotnet nuget push /drone/src/SimpleWorkflow/bin/Debug/SimpleWorkflow.1.0.0.nupkg --api-key $nuget_api_key --source https://repository.decryptology.net/repository/Nuget/index.json

