kind: pipeline

steps:
- name: test
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  commands:
  - dotnet test --logger "console;verbosity=detailed"
- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  environment:
    nuget_api_key:
      from_secret: nuget_api_key
  commands:
  - dotnet pack
  - dotnet nuget push /drone/src/SimpleWorkflow/bin/Debug/SimpleWorkflow.1.0.0.nupkg --api-key $nuget_api_key --source https://repository.decryptology.net/repository/Nuget/index.json

