kind: pipeline

steps:
- name: test
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  environment: 
    repo_username:
      from_secret: repo_username
    repo_password:
      from_secret: repo_password
  commands:
  - export PATH="$PATH:/root/.dotnet/tools"
  - dotnet tool install -g dotnet-reportgenerator-globaltool
  - dotnet test --logger "console;verbosity=detailed" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - reportgenerator -reports:/drone/src/SimpleWorkflow.Test/coverage.opencover.xml -targetdir:/drone/src/SimpleWorkflow.Test/report -reporttypes:"Badges;Html" -title:"SimpleWorkflow Code Coverage"
- name: upload
  image: plugins/s3
  settings:
    bucket: code-coverage
    access_key:
      from_secret: access_key
    secret_key:
      from_secret: secret_key
    source: /drone/src/SimpleWorkflow.Test/report/*
    target: /SimpleWorkflow.Test
    path_style: true
    strip_prefix: /drone/src/SimpleWorkflow.Test/report
    endpoint: https://s3.decryptology.net
- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  environment:
    nuget_api_key:
      from_secret: nuget_api_key
  commands:
  - dotnet pack
  - dotnet nuget push /drone/src/SimpleWorkflow/bin/Debug/SimpleWorkflow.1.0.0.nupkg --api-key $nuget_api_key --source https://repository.decryptology.net/repository/Nuget/index.json

