kind: pipeline

steps:
- name: test
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  environment: 
    repo_username:
      from_secret: repo_username
    repo_password:
      from_secret: repo_password
  commands:
  - export PATH="$PATH:/root/.dotnet/tools"
  - dotnet tool install -g dotnet-reportgenerator-globaltool
  - dotnet test --logger "console;verbosity=detailed" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - reportgenerator -reports:/drone/src/SimpleWorkflow.Test/coverage.opencover.xml -targetdir:/drone/src/SimpleWorkflow.Test/report -reporttypes:"Html" -title:IntegrationTest
  - curl -v -u $repo_username:$repo_password --upload-file /drone/src/SimpleWorkflow.Test/report/index.html https://repository.decryptology.net/repository/artifacts/SimpleWorkflow.Test/code-coverage.html
- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  environment:
    nuget_api_key:
      from_secret: nuget_api_key
  commands:
  - dotnet pack
  - dotnet nuget push /drone/src/SimpleWorkflow/bin/Debug/SimpleWorkflow.1.0.0.nupkg --api-key $nuget_api_key --source https://repository.decryptology.net/repository/Nuget/index.json

