kind: pipeline

steps:
- name: test
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  commands:
  - dotnet tool install --global coverlet.console
  - dotnet test --collect:"XPlat Code Coverage" --logger "console;verbosity=detailed"
- name: build
  image: microsoft/dotnet:sdk
  environment:
    nuget_api_key:
      from_secret: nuget_api_key
  commands:
  - dotnet pack
  - dotnet nuget push /drone/src/SimpleWorkflow/bin/Debug/SimpleWorkflow.1.0.0.nupkg --api-key $nuget_api_key --source https://repository.decryptology.net/repository/Nuget/index.json

